<?php
namespace App\Repositories\Entrust;

use App\Entities\Entrust\Role;
use App\Repositories\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;

class RoleRepository extends BaseRepository
{

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Role::class;
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $this->pushCriteria(app(RequestCriteria::class));
    }
}